config/routes.rb
GaMapQuote::Application.routes.draw do
  root to: "pages#root"

  get "/about", to: "pages#about"

  get "quotes/index"

  devise_for :admins
  devise_for :users

  resources :users, only: [ :edit, :update ]

  resources :quotes, only: [ :index, :new, :create, :show, :edit, :update, :destroy ]

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :user
    validates :quote, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :quotes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :registerable
  # :registerable has been removed to make the site by invitation only
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :invitable,:registerable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  before_filter :authenticate!, except: :index

  def index
    @quotes = Quote.all
  end

  def new
    @quote = Quote.new
  end

  def create
    quote = Quote.create quote_params
    flash[:notice] = "Thanks for submitting a quote!"
    redirect_to quote
  end

  def update
    @quote = Quote.find params[:id]
    quote.update_attributes!(quote_params)
    quote = Quote.update quote_params
  end

  def show
    @quote = Quote.find params[:id]
    @quotes = Quote.all
  end

  def edit
    @quote = Quote.find params[:id]
    quote = Quote.update quote_params
    redirect_to @quote
  end

  private

  def quote_params
    params.require(:quote).permit(:quote)
  end

  def authenticate!
    redirect_to root_path unless user_signed_in? or admin_signed_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate!, except: :index

  def index
    @users = User.all
  end

  def new
    @user = User.create
  end

  def create
    user = User.create user_params
  end

  def update
    @user = User.find params[:id]
    user.update_attributes!(user_params)
    user = User.update user_params
  end

  def show
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]
    user = User.update user_params
  end

  private

  def authenticate!
  redirect_to root_path unless user_signed_in? or admin_signed_in?
  end

  def user_params
    params.require(:user).permit(:email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/quote_helper.rb
module QuoteHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Map Quote of the Day</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <nav class="navbar navbar-default  navbar-fixed-top" role="navigation">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Map Quote of the Day", root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Too much coffee. Not enough sleep. Lots of coding.", about_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Quotes<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <!-- <li><a href="#">Map</a></li>
            <li><a href="#">Reduce</a></li> -->
            <li class="divider"></li>
            <li><%= link_to "View All", quotes_path %></li>
          </ul>
        </li>
        <%= form_tag '/search', class: "navbar-form navbar-right", method: :get do  %>
      <div>
        <%= text_field_tag 'q', nil, :placeholder => "Search", class: "form-control navbar-form" %>
        <%= submit_tag "Go!", class: "btn btn-default" %>
      </div>
    <% end %>

          <!-- devise -->
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? || admin_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "View Profile", current_user %></li>
                  <li><%#= link_to "Edit Profile", edit_user_path(@user) %></li>
                </ul>
               <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, class: 'navbar-link' %></li>
          <% else %>
            <li><%= link_to "Log In", new_user_session_path, class: 'navbar-link' %></li>
            <li><%= link_to "Sign Up", new_user_registration_path, class: 'navbar-link' %></li>
          <% end %>
        </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<br />
<br />
<h4>Map Quote of the Day is a pet project that got started one day at lunch. Over a discussion about tupperware.</h4>
<br />
<p>This site a place for my class to remember fun moments that happened during the three-month journey we're taking to become full stack web developers. We'll be using it to store great memories.</p>

app/views/pages/index.html.erb
<div id="quote">"I thought you said Anne Frank."</div>

<div id="comment">
  <span class="glyphicon glyphicon-comment img-responsive"></span>
</div>
<%= link_to "Submit a Quote for Approval", new_quote_path(@quote), class:"btn btn-default btn-md" %>

app/views/pages/root.html.erb
<div id="quote">"I call it To_Proc Shakur."

<br />

<%= link_to "Submit a Quote for Approval", new_quote_path(@quote), class: "btn btn-default btn-md" %>

</div>

<div id="commentglyph">
  <span class="glyphicon glyphicon-comment img-responsive"></span>
</div>

app/views/quote/index.html.erb
<div id="quote">"I thought you said Anne Frank."</div>

<div id="comment">
  <span class="glyphicon glyphicon-comment img-responsive"></span>
</div>

app/views/quotes/edit.html.erb
<div class="col-md-6">

  <h1>Edit a quote for approval: </h1>
  <%= form_for @quote do |f| %>

    <br />

    <h4><%= f.label :quote %></h4>
      <%= f.text_field :quote, placeholder: "Edit the Quote", class: "form-control" %><br />

    <div><%= f.submit "Submit Edit", class: "btn btn-default btn-md" %></div>
  <% end %>

</div>

app/views/quotes/index.html.erb
<div id="quotesindex">
  <h2>Here's a list of user-submitted quotes:</h2>
    <% @quotes.each do |quote| %>
      <ul>
        <li><%= link_to quote.quote, quote %></li>
      </ul>
    <% end %>
</div>

app/views/quotes/new.html.erb
<div class="col-md-6">

  <h1>Submit a quote for approval: </h1>
  <%= form_for @quote do |f| %>

    <br />

    <h4><%= f.label :quote %></h4>
      <%= f.text_field :quote, placeholder: "Type the quote you want to add.", class: "form-control" %><br />

    <div><%= f.submit "Submit Quote", class: "btn btn-default btn-md" %></div>
  <% end %>

</div>

app/views/quotes/show.html.erb
<div class="col-6-md">
  <h4><%= @quote.quote %></h4>

  <%= link_to "Submit Another Quote", new_quote_path(@quote), class: "btn btn-default btn-md" %>
<br />
<br />
  <%= link_to "Home", root_path, class: "btn btn-default btn-md" %>
</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>